[build]
  # Optional: command to build your site (if needed)
  # command = "npm run build"
  # Optional: directory containing your built site files
  # publish = "dist"

[functions]
  # Directory where your serverless functions live
  directory = "netlify/functions/"
  # Ensure Node.js dependencies for functions are installed
  node_bundler = "esbuild" # Or "zisi" if you prefer
